### ISSUE TITLE
Pedestrian multiplier values

### ISSUE THREAD

**Issue by jslason** [RSGInc/ladot_analysis_dataprep#8]
Are these [pedestrian multipliers](https://github.com/RSGInc/ladot_analysis_dataprep#pedestrian) correct? Based on the bike values, the we should have a higher than 1 value when it is less attractive than a 'base' or 'normal' condition. 
 
@bstabler

**Comment by bstabler** [comment]
https://github.com/RSGInc/ladot_analysis_dataprep#pedestrian

**Comment by bstabler** [comment]
I think they might need to be 1.* values.  @mxndrwgrdnr?

**Comment by bstabler** [comment]
@ansoncfit notes that Conveyal calculates the generalized cost correctly on their side based on the raw input values

**Comment by mxndrwgrdnr** [comment]
These multipliers are correct based on how the penalties are applied (see [here](https://github.com/RSGInc/ladot_analysis_dataprep/blob/master/osm_gen_costs.py#L739-L740). If we converted 0.99 to 1.99 we would be double-counting distance. Instead of baking in the base distance to each individual term we just add it once as a standalone term outside of any distance-dependent penalty. In the documentation, we simply call this the distance term and apply a 1.0 multiplier, which can be seen in the first row of the table you linked @jslason as well as the analogous [table](https://github.com/RSGInc/ladot_analysis_dataprep#bicycle) for the bike gen cost.

**Comment by bstabler** [comment]
Great, thanks
